name: Pipeline

on:
    push:
        branches:
            - master
    workflow_dispatch:
        branches:
            - master

jobs:
    runner:
        strategy:
            matrix:
                os: [ ubuntu-24.04, ubuntu-24.04-arm, windows-2025, windows-11-arm, macos-13, macos-15 ]
        runs-on: ${{ matrix.os }}
        permissions:
            contents: read
        timeout-minutes: 5
        steps:
            -   uses: actions/checkout@v4

            -   name: Detect platform
                uses: thaitype/actions-switch-case@v1
                id: platform
                with:
                    default: "unknown"
                    conditionals-with-values: |
                        ${{ matrix.os == 'ubuntu-24.04' }} => ubuntu-x64
                        ${{ matrix.os == 'ubuntu-24.04-arm' }} => ubuntu-arm64
                        ${{ matrix.os == 'windows-2025' }} => windows-x64
                        ${{ matrix.os == 'windows-11-arm' }} => windows-arm64
                        ${{ matrix.os == 'macos-13' }} => macos-x64
                        ${{ matrix.os == 'macos-15' }} => macos-arm64

            -   name: Show platform
                run: |
                    echo "Platform: ${{ steps.platform.outputs.match }}"

            -   name: Setup Java
                uses: actions/setup-java@v4
                with:
                    distribution: 'temurin'
                    java-version: '23'

            -   name: Setup agent
                run: |
                    curl -sO "${{ secrets.MANAGER_URL }}/jnlpJars/agent.jar"
                working-directory: ${{ github.workspace }}

            -   name: Set secret
                uses: thaitype/actions-switch-case@v1
                id: secret
                with:
                    default: "unknown"
                    conditionals-with-values: |
                        ${{ steps.platform.outputs.match == 'ubuntu-x64' }} => ${{ secrets.AGENT_SECRET_UBUNTU_X64 }}
                        ${{ steps.platform.outputs.match == 'ubuntu-arm64' }} => ${{ secrets.AGENT_SECRET_UBUNTU_ARM64 }}
                        ${{ steps.platform.outputs.match == 'windows-x64' }} => ${{ secrets.AGENT_SECRET_WINDOWS_X64 }}
                        ${{ steps.platform.outputs.match == 'windows-arm64' }} => ${{ secrets.AGENT_SECRET_WINDOWS_ARM64 }}
                        ${{ steps.platform.outputs.match == 'macos-x64' }} => ${{ secrets.AGENT_SECRET_MACOS_X64 }}
                        ${{ steps.platform.outputs.match == 'macos-arm64' }} => ${{ secrets.AGENT_SECRET_MACOS_ARM64 }}

            -   name: Run agent
                run: |
                    java -jar agent.jar -url ${{ env.MANAGER_URL }}/ -secret ${{ env.AGENT_SECRET }} -name ${{ env.AGENT_NAME }} -webSocket -workDir ${{ env.WORK_DIR }}
                working-directory: ${{ github.workspace }}
                env:
                    MANAGER_URL: ${{ secrets.MANAGER_URL }}
                    AGENT_SECRET: ${{ steps.secret.outputs.match }}
                    AGENT_NAME: ${{ steps.platform.outputs.match }}
                    WORK_DIR: ${{ github.workspace }}
