name: Pipeline

on:
    push:
        branches:
            - master
    workflow_dispatch:
        branches:
            - master

jobs:
    runner:
        strategy:
            matrix:
                os: [ ubuntu-24.04, ubuntu-24.04-arm, windows-2025, windows-11-arm, macos-13, macos-15 ]
        runs-on: ${{ matrix.os }}
        permissions:
            contents: read
        steps:
            -   uses: actions/checkout@v4
            -   uses: actions/setup-java@v4
                with:
                    distribution: 'temurin'
                    java-version: '23'
            -   run: java --version
